name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: meta
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pedidos-cliente:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pedidos-cliente:latest
          platforms: linux/amd64,linux/arm64
